database:
  host: "localhost"
  database: "your_database"
  user: "your_user"
  password: "your_password"
  port: "3306"

timezone: "UTC"

email:
  smtpAuth: "true"
  startTls: "true"
  host: "smtp.gmail.com"
  port: "587"
  username: "your_email"
  password: "your_password"
