database:
  host: "localhost"
  database: "carsbase"
  user: "root"
  password: "Igorpro2020#@"
  port: "3306"

timezone: "UTC"

email:
  smtpAuth: "true"
  startTls: "true"
  host: "smtp.gmail.com"
  port: "587"
  username: "sprezzari@gmail.com"
  password: "rbgrddroogfioash"